//
//  CountryWeatherPresenter.swift
//  Sandro Giorgishvili 28
//
//  Created by TBC on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryWeatherPresentationLogic
{
    func presentCountryWeather(response: CountryWeather.ShowCountryWeather.Response)
}

class CountryWeatherPresenter: CountryWeatherPresentationLogic
{
    weak var viewController: CountryWeatherDisplayLogic?
    
    func presentCountryWeather(response: CountryWeather.ShowCountryWeather.Response) {
        guard let mainWeather = response.countryWeahterData.weather.first?.main else { return }
        viewController?.displaySelectedCountryWeather(viewModel: CountryWeather.ShowCountryWeather.ViewModel(currentWeather: mainWeather))
    }
}
