//
//  CountriesRouter.swift
//  Sandro Giorgishvili 28
//
//  Created by TBC on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountriesRoutingLogic {
    func navigateToCountryDetails()
}

protocol CountriesDataPassing {
    var dataStore: CountriesDataStore { get }
}

class CountriesRouter: NSObject, CountriesRoutingLogic, CountriesDataPassing
{
    weak var viewController: CountriesViewController?
    private(set) var dataStore: CountriesDataStore
    
    init(dataStore: CountriesDataStore) {
        self.dataStore = dataStore
    }
    
    func navigateToCountryDetails() {
        guard let selectedCountry = dataStore.selectedCountry else { return }      
        let destinationVC = CountryWeatherConfigurator.configure(with: selectedCountry)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}
