//
//  CountriesModels.swift
//  Sandro Giorgishvili 28
//
//  Created by TBC on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Countries
{
    // MARK: Use cases
    
    enum GetCountries {
        struct Request { }
        
        struct Response {
            let data: [Country]
        }
        
        struct ViewModel {
            let tableData: [AbstractModel]
        }
    }
    
    enum ShowCountryDetails {
        struct Request {
            let selectedCountryName: String
        }
        
        struct Response { }
        
        struct ViewModel { }
    }
    
    enum FilterCountries {
        struct Request {
            let keyword: String
        }
        
        struct Response {
            let data: [Country]
        }
        
        struct ViewModel {
            let tableData: [AbstractModel]
        }
    }
}
